config/routes.rb
Rails.application.routes.draw do
  root "games#index"
  get "up" => "rails/health#show", as: :rails_health_check

  resources :games
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  def neverplayed?
    length.blank? || length.zero?
  end
  def playthrough?
    case length
    when 30..99
      'average'
    when 100
      'prolonged'
    else
      'brief'
    end
  end
end

app/models/tyme.rb
class Tyme < ApplicationRecord
  def nonexistent?
    length.blank? || length.zero?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end
  def show
    @game = Game.find(params[:id])
  end

  def edit
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    game_params = 
      params.require(:game)
        .permit(:name,:description,:length,:starts_at,:ends_at)
    @game = Game.new(game_params)
    @game.save
    redirect_to @game
  end

  def update
    @game = Game.find(params[:id])
    game_params = 
      params.require(:game)
        .permit(:name,:description,:length,:starts_at,:ends_at)
    @game.update(game_params)
    redirect_to @game
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  def gamestate(game)
    if game.neverplayed?
      "Start"
    else
      "Continue"
    end
  end
  def ptlength(game)
    game.playthrough?
  end
end

app/helpers/timez_helper.rb
module TimezHelper
end

app/views/games/edit.html.erb
<p>editing game</p>

<%= form_with model: @game do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :description %>
  <%= form.text_area :description %>

  <%= form.label :length %>
  <%= form.number_field :length %>

  <%= form.submit%>
<% end %>

app/views/games/index.html.erb
<ul>
  <% @games.each do |game| %>
    <li>
      <%= link_to game.name, game%>
      <p><%= game.description %></p>
    </li>
  <% end %>
</ul>

<%= link_to "add new", new_game_path %>

app/views/games/new.html.erb
<p>making game</p>

<%= form_with model: @game do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :description %>
  <%= form.text_area :description %>

  <%= form.label :length %>
  <%= form.number_field :length %>

  <%= form.submit%>
<% end %>

app/views/games/show.html.erb
<%= link_to "All games", games_path%>
<h3><%= @game.name %></h3>
<p><%= @game.description %></p>
<p><%= gamestate(@game) %></p>
<p>Playthrough time: <%= ptlength(@game) %></p>

<%= link_to "edit", edit_game_path(@game)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rubee" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%# TODO: restore once you figure out how %>
    <%# <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%# <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/timez/index.html.erb
<ul>
  <% @timez.each do |time| %>
    <li><%= time %></li>
  <% end %>
</ul>

app/views/tymez/edit.html.erb
<p>editing tyme</p>

<%= form_with(model: @tymez) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :description %>
  <%= form.text_area :description %>

  <%= form.label :length %>
  <%= form.number_field :length %>

  <%= form.label :starts_at %>
  <%= form.datetime_select :starts_at %>

  <%= form.label :ends_at %>
  <%= form.datetime_select :ends_at %>

  <%= form.submit%>
<% end %>